import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "True"

import streamlit as st
import cv2
import requests
from PIL import Image
from glob import glob
from numpy import random
import io
import torch
from ultralytics import YOLO


# -------------------------
# Model utilities
# -------------------------
def load_model(model_path):
    model = YOLO(model_path)
    return model


def predict_image(model, image, conf_threshold, iou_threshold):
    res = model.predict(
        image,
        conf=conf_threshold,
        iou=iou_threshold,
        device="cpu",
    )

    class_name = model.model.names
    classes = res[0].boxes.cls
    class_counts = {}

    for c in classes:
        c = int(c)
        class_counts[class_name[c]] = class_counts.get(class_name[c], 0) + 1

    prediction_text = "Predicted "
    for k, v in sorted(class_counts.items(), key=lambda item: item[1], reverse=True):
        prediction_text += f"{v} {k}"
        if v > 1:
            prediction_text += "s"
        prediction_text += ", "

    prediction_text = prediction_text[:-2]
    if not class_counts:
        prediction_text = "No objects detected"

    latency = round(sum(res[0].speed.values()) / 1000, 2)
    prediction_text += f" in {latency} seconds."

    res_image = res[0].plot()
    res_image = cv2.cvtColor(res_image, cv2.COLOR_BGR2RGB)

    return res_image, prediction_text


# -------------------------
# Main App
# -------------------------
def main():
    st.set_page_config(
        page_title="Wildfire Detection",
        page_icon="🔥",
        initial_sidebar_state="collapsed",
    )

    # Sidebar
    st.sidebar.markdown("Developed by Shreshth Srivastav")
    st.sidebar.markdown("GitHub: https://github.com/shoka1280/wildfire-detection")

    # Title
    st.markdown("<h1 style='text-align:center;'>🔥 Wildfire Detection</h1>", unsafe_allow_html=True)

    # Logo
    logos = glob("dalle-logos/*.png")
    if logos:
        logo = random.choice(logos)
        st.image(logo, use_column_width=True, caption="Generated by DALL·E")
        st.sidebar.image(logo, use_column_width=True)

    st.markdown("---")

    # Model selection
    col1, col2 = st.columns(2)
    with col1:
        model_type = st.radio("Select Model Type", ("Fire Detection", "General"))

    models_dir = "general-models" if model_type == "General" else "fire-models"
    model_files = [f.replace(".pt", "") for f in os.listdir(models_dir) if f.endswith(".pt")]

    with col2:
        selected_model = st.selectbox("Select Model Size", sorted(model_files))

    model_path = os.path.join(models_dir, selected_model + ".pt")
    model = load_model(model_path)

    st.markdown("---")

    # Thresholds
    col1, col2 = st.columns(2)
    with col1:
        iou_threshold = st.slider("IOU Threshold", 0.0, 1.0, 0.5, 0.05)
    with col2:
        conf_threshold = st.slider("Confidence Threshold", 0.0, 1.0, 0.20, 0.05)

    st.markdown("---")

    # Image input
    image = None
    image_source = st.radio("Select image source:", ("Enter URL", "Upload from Computer"))

    if image_source == "Upload from Computer":
        uploaded_file = st.file_uploader("Upload an image", type=["png", "jpg", "jpeg"])
        if uploaded_file is not None:
            image = Image.open(uploaded_file)

    else:
        url = st.text_input("Enter the image URL:")
        if url:
            try:
                response = requests.get(url, stream=True, timeout=10)
                if response.status_code == 200:
                    image = Image.open(response.raw)
                else:
                    st.error("Invalid image URL.")
            except Exception as e:
                st.error(f"Error loading image: {e}")

    # Detection
    if image is None:
        st.warning("Please upload an image or enter a valid direct image URL.")
    else:
        with st.spinner("Detecting..."):
            prediction, text = predict_image(
                model, image, conf_threshold, iou_threshold
            )

        st.image(prediction, caption="Prediction", use_column_width=True)
        st.success(text)

        buffer = io.BytesIO()
        Image.fromarray(prediction).save(buffer, format="PNG")

        st.download_button(
            label="Download Prediction",
            data=buffer.getvalue(),
            file_name="prediction.png",
            mime="image/png",
        )


if __name__ == "__main__":
    main()
